import numpy as np
import matplotlib.pyplot as plt

data50 = np.load("Simulation-n50.npz")
data100 = np.load("Simulation-n100.npz")
data250 = np.load("Simulation-n250.npz")
data750 = np.load("Simulation-n750.npz")

fig, axs = plt.subplots(5, 4, figsize=(17, 12)) #sharey=ax1
plt.setp(axs, xticks=[1,2,3,4], xticklabels=['SDGM','SDGM-C','GVA-SAS', 'SDGM-SAS'])
axs[0, 0].boxplot(data50['mu_matrix'])
axs[0, 0].set_title('n=50',size=15)
axs[0, 0].set_ylabel('mean',fontsize = 15)
axs[1, 0].boxplot(data50["sigma_matrix"])
axs[1, 0].set_ylabel('SD',fontsize = 15)
axs[2, 0].boxplot(data50["k_matrix"])
axs[2, 0].set_ylabel('skewness',fontsize = 15)
axs[3, 0].boxplot(data50["pll_matrix"])
axs[3, 0].set_ylabel('Pred.LL',fontsize = 15)
axs[4, 0].boxplot(data50["acc_matrix"])
axs[4, 0].set_ylabel('Pred.acc',fontsize = 15)

axs[0, 1].boxplot(data100['mu_matrix'])
axs[0, 1].set_title('n=100',size=15)
axs[1, 1].boxplot(data100["sigma_matrix"])
axs[2, 1].boxplot(data100["k_matrix"])
axs[3, 1].boxplot(data100["pll_matrix"])
axs[4, 1].boxplot(data100["acc_matrix"])

axs[0, 2].boxplot(data250['mu_matrix'])
axs[0, 2].set_title('n=250',size=15)
axs[1, 2].boxplot(data250["sigma_matrix"])
axs[2, 2].boxplot(data250["k_matrix"])
axs[3, 2].boxplot(data250["pll_matrix"])
axs[4, 2].boxplot(data250["acc_matrix"])

axs[0, 3].boxplot(data750['mu_matrix'])
axs[0, 3].set_title('n=750',size=15)
axs[1, 3].boxplot(data750["sigma_matrix"])
axs[2, 3].boxplot(data750["k_matrix"])
axs[3, 3].boxplot(data750["pll_matrix"])
axs[4, 3].boxplot(data750["acc_matrix"])

axs[0, 0].xaxis.set_visible(False)
axs[1, 0].xaxis.set_visible(False)
axs[2, 0].xaxis.set_visible(False)
axs[3, 0].xaxis.set_visible(False)
axs[0, 1].xaxis.set_visible(False)
axs[1, 1].xaxis.set_visible(False)
axs[2, 1].xaxis.set_visible(False)
axs[3, 1].xaxis.set_visible(False)
axs[0, 2].xaxis.set_visible(False)
axs[1, 2].xaxis.set_visible(False)
axs[2, 2].xaxis.set_visible(False)
axs[3, 2].xaxis.set_visible(False)
axs[0, 3].xaxis.set_visible(False)
axs[1, 3].xaxis.set_visible(False)
axs[2, 3].xaxis.set_visible(False)
axs[3, 3].xaxis.set_visible(False)


axs[4, 0].set_xticks(ticks=[1,2,3,4], labels=['SDGM','SDGM-C','GVA-SAS', 'SDGM-SAS'],rotation=50)
axs[4, 1].set_xticks(ticks=[1,2,3,4], labels=['SDGM','SDGM-C','GVA-SAS', 'SDGM-SAS'],rotation=50)
axs[4, 2].set_xticks(ticks=[1,2,3,4], labels=['SDGM','SDGM-C','GVA-SAS', 'SDGM-SAS'],rotation=50)
axs[4, 3].set_xticks(ticks=[1,2,3,4], labels=['SDGM','SDGM-C','GVA-SAS', 'SDGM-SAS'],rotation=50)


axs[0, 0].tick_params(labelsize=10)
axs[1, 0].tick_params(labelsize=10)
axs[2, 0].tick_params(labelsize=10)
axs[3, 0].tick_params(labelsize=10)
axs[4, 0].tick_params(labelsize=10)
axs[0, 1].tick_params(labelsize=10)
axs[1, 1].tick_params(labelsize=10)
axs[2, 1].tick_params(labelsize=10)
axs[3, 1].tick_params(labelsize=10)
axs[4, 1].tick_params(labelsize=10)
axs[0, 2].tick_params(labelsize=10)
axs[1, 2].tick_params(labelsize=10)
axs[2, 2].tick_params(labelsize=10)
axs[3, 2].tick_params(labelsize=10)
axs[4, 2].tick_params(labelsize=10)
axs[0, 3].tick_params(labelsize=10)
axs[1, 3].tick_params(labelsize=10)
axs[2, 3].tick_params(labelsize=10)
axs[3, 3].tick_params(labelsize=10)
axs[4, 3].tick_params(labelsize=10)
# plt.show()
plt.savefig(f"Boxplot-simulation.pdf")
